version: "3.8"

services:
  database:
    image: mysql:8.0.33
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: myDB
    ports:
      - "3307:3306"


  backend:
    container_name: backend
    env_file:
      .env
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
#      SPRING_DATASOURCE_URL: jdbc:mysql://database:3307/myDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - database
    restart: on-failure
